runtime:
  cache_dir: ./.cache/antora

site:
  title: OpenShift Cloud Functions (OCF)
  url: https://openshift-cloud-functions.github.io/Documentation/
  start_page: openshift-cloud-functions::index

content:
  sources:
    - url: https://github.com/openshift-cloud-functions/Documentation.git
      tags: v*
      branches: master
      
asciidoc:
  attributes:
    tutorial-namespace: Serverless
  extensions:
    - ./lib/copy-to-clipboard.js
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
output:
  dir: ./gh-pages
